name: Build toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: crosstool-ng/crosstool-ng
          
      - name: Install crosstool-ng
        run: |
          sudo apt update && sudo apt install -y help2man libtool-bin
          ./bootstrap
          ./configure --prefix=/usr
          make
          sudo make install
          
      - uses: actions/checkout@v2
        
      - name: Build arm64
        run: |
          cd arm64
          ct-ng build; true
          cat build.log
