name: Build toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
   
      - name: Install crosstool-ng
        run: |
          wget https://blog.gamecss.ga/ct-ng-build/crosstool-ng.deb
          sudo dpkg -i crosstool-ng.deb
        
      - name: Build arm64
        run: |
          cd arm64
          ct-ng build
      - name: Upload error log
        uses: actions/upload-artifact@v2.2.4
        if: ${{ failure() }}
        with:
          name: build.log
          path: build.log
